---
title: "Discussion Section Syllabus for A04, A05, & A06"
---

::: callout-important
The syllabus is subject to changes and updates.
:::

Welcome! Each section is an opportunity for students to meet in smaller groups and learn from each other about course material. Students are encouraged to use sections as a place to seek clarification and ask questions about course concepts. Section will hold active discussion to further understand topics about research methods.

## Course info

+-----------------+-----------------+--------------------------+-----------------+
|                 | Day             | Time                     | Location        |
+=================+=================+==========================+=================+
| Lectures        | Tue & Thur.     | 3:10 pm - 4:30 pm        | Wellman 2       |
+-----------------+-----------------+--------------------------+-----------------+
| Discussion/Lab  | Fri.            | A04: 9:00 AM - 9:50 AM   | Kerr Hall 451   |
|                 |                 |                          |                 |
|                 |                 | A05: 10:00 AM - 10:50 AM |                 |
|                 |                 |                          |                 |
|                 |                 | A06: 11:00 AM - 11:50 AM |                 |
+-----------------+-----------------+--------------------------+-----------------+
| Office Hours    | Tue             | 12:00 - 3:00 PM          | Kerr Hall 569   |
+-----------------+-----------------+--------------------------+-----------------+

## Learning objectives

By the end of this course you will be able to...

-   Analyze real-world data to answer questions about different relationships.
-   Feel comfortable manipulating data in R
-   Craft effective visualizations of patterns in data
-   Draw causal diagrams and identify obstacles to causal claims
-   Understand the basics of regression and uncertainty

## Attendance

Attendance is mandatory. I will come to the section on time and prepared and expect no less from each student. As such, please arrive on time, be ready to listen, ask questions, and engage in conversation.

## Communication

-   What are office hours for?
    -   Office hours are when the professor sets aside two hours each week making themselves available to students. Office hours are often underutilized by all students in college. Consider this your time.
    -   You do not need an appointment to come by.
    -   My job as a Professor is to help each of you succeed; however, I can only help you if you ask. (PLEASE COME ASK ME!)
    -   I strongly encourage students to come to my office hours and chat about topics from the readings or lectures, talk over potential study strategies, or to simply converse.
-   What are Emails for?
    -   If your question cannot wait until office hours, section, or class, then students should/may use email to contact their Professor. However, please note, email should not be used as an alternative to direct conversation or an in-depth discussion.
    -   As a simple rule of thumb, emails should be used to address quick questions, not for requests to exhaustively review material from lecture or section.
    -   I will respond to emails within one business day, so between 9 am and 6 pm on weekdays. This means if you email me past 6 pm on a weekday you will not receive any email till the next day in the morning around 9 am. If you email me on the weekends or past Friday at 6 pm, I will respond promptly on Monday.
    -   I will not respond to emails that are rude, unintelligible, or inquiring about information readily accessible on the syllabus.
-   I will typically communicate announcements through Canvas. Please make sure your Canvas information is up to date and that you check it frequently over the quarter.

## Participation Assessment

Participation assessment for discussion section will be graded based upon attendance. Attendance will be counted based upon the compilation on signing in at the beginning of class or submitting the exercises we did during class on Canvas. Any exercise submissions will not be graded based on correctness but on showing effort.

Our section will only be successful if we all participate and learn together. It is expected for everyone to participate over the course of the quarter. Participation includes asking questions in class, completing in-class activities and contributing to discussion.

-   This is a political science course, and as such we will be discussing political issues. As each of us comes into the section with unique opinions about political issues, there may be disagreements. I insist we discuss our differences with respect, civility, and empathy. Please do your best to keep an open mind about your peers’ perspectives as your peers will expect the same of you.

-   Note: This does not mean you should avoid participating if/when you have an alternative point of view just because you may not wish to provoke an argument. Be bold, and share what you think (respectfully).

    -   If I believe any of the discussion is becoming disrespectful or includes hateful or inappropriate speech, I hold the right to end the discussion.

### One FREE absence.

If there are circumstances that prevent you from attending section, you receive one free excused absence. I will NOT be providing any make-up assignments. Please do not email me that you will be absent; this will be taken into account if you attend all sections or you attend none.

If you are absent due to illness, religious reasons, etc., please email me directly. Please note that work conflicts are not considered an excused absence.

## Course policies

### Academic integrity

Cheating and plagiarism will be evaluated and disciplined according to University policy. For information on academic integrity, please read: <http://cai.ucdavis.edu/aip.html>. You are responsible for understanding and following all aspects of University policy on academic integrity; ignorance is not an excuse. All suspected violations will be referred to Student Judicial Affairs for evaluation. You will be notified promptly by email if a referral is made.

### Policy on sharing and reusing code

I am well aware that a huge volume of code is available on the web to solve any number of problems. Unless I explicitly tell you not to use something, the course's policy is that you may make use of any online resources (e.g. RStudio Community, StackOverflow).

### Policy on AI

AI is not allowed for usage in this classroom to do any assignment or work in place of yourself. You may not use artificial intelligence tools such as ChatGPT, Gemini, Claude, Grok, etc. to complete any academic work in its entirety being submitted for credit in the UC Davis Department of Political Science. The Office of Student Support and Judicial Affairs (OSSJA) considers the unauthorized use of content generated by artificial intelligence (AI) to be academic misconduct and/or plagiarism (see: <https://ossja.ucdavis.edu/code-academic-conduct>).

Taking credit for any work not created by the student; work includes, but is not limited to, books, articles, experimental methodology or results, compositions, images, lectures, computer programs, internet postings, and content generated by software or artificial intelligence.

### Regrade request policy

Regrade requests must be submitted within a week of when an assignment is returned. A regrade request will be considered if there was an error in the grade calculation or if you feel a correct answer was mistakenly marked as incorrect. Requests to dispute the number of points deducted for an incorrect response will not be considered. Note that by submitting a regrade request, the entire question will be graded which could potentially result in losing points.

*No grades will be changed after the final project presentations.*

### Policy on video recording course content

If you feel that you need to record the lectures yourself, you must get permission from me ahead of time and these recordings should be used for personal study only, not for distribution. Unauthorized distribution is a cause for disciplinary action by the Judicial Board.

*Note:* If you've read this far in the syllabus, email me a picture of your pet if you have one or your favorite meme for extra credit!

## Community and UC Davis Policies

### Inclusive community

It is my intent that students from all diverse backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength, and benefit. It is my intent to present materials and activities that are respectful of diversity. Your suggestions are encouraged and appreciated.

Please note that this is a political science course, and as such we will be discussing political issues. As each of us comes into the section with unique opinions about political issues, there may be disagreements. I insist we discuss our differences with respect, civility, and empathy. Please do your best to keep an open mind about your peers’ perspectives as your peers will expect the same of you.

*Note*: This does not mean you should avoid participating if/when you have an alternative point of view just because you may not wish to provoke an argument. Be bold, and share what you think (respectfully).

-   *If I believe any of the discussion is becoming disrespectful or includes hateful or inappropriate speech, I hold the right to end the discussion.*

### Accessibility

If there is any portion of the course that is not accessible to you due to challenges with technology or the course format, please let me know so we can make appropriate accommodations.

It is the Professor’s responsibility to help make this course accessible to all students. If you believe you have a disability requiring an accommodation or would like additional information about the resources available for students with disabilities, please visit the UC Davis Student Disability Center website at [sdc.ucdavis.edu](https://sdc.ucdavis.edu).

-   Students must contact me about any accommodations in advance.

-   Outside Resources - The Student Academic Success Center is a campus-wide resource assisting students by helping them improve in study skills, academic writing, and other specific topics.

### Mandatory Reporter

In my role as faculty, **I am required by policy to report concerns that come to my attention related to sexual harassment, sexual violence, discrimination, or harassment involving students.**  Please know you are still free to discuss these concerns with me, but I will need to pass along any information shared with me to the Harassment and Discrimination Assistance and Prevention Program (HDAPP) so they can reach out to you and talk to you about resources and possible resolution options.  If you would prefer to speak to a confidential resource, who does not have the same responsibility to report, I can help you get connected. 

Alternatively, here is a link to information about available resources on campus (including confidential resources):  <https://hdapp.ucdavis.edu/resources>.  Also, here is a link to information about reporting directly to HDAPP:  <https://hdapp.sf.ucdavis.edu/report-incident>.

### **Counseling & Psychiatry Services**

Life at Davis can be complicated and challenging. You might feel overwhelmed, experience anxiety or depression, or struggle with relationships or family responsibilities. [UC Davis Counseling Services](https://shcs.ucdavis.edu/services/counseling-services) provide *confidential* support for students who are struggling with mental health and emotional challenges. Please do not hesitate to contact them for assistance—getting help is a smart and good thing to do.

### Copyright

My lectures and course materials, including presentations, essay questions, outlines, exams, and similar materials, are protected by U.S. copyright law and by University policy. I am the exclusive owner of the copyright in those materials I create. You may take notes and make copies of course materials for your own use. You may also share those materials with another student who is enrolled in or auditing this course. You may not reproduce, distribute or display (post/upload) lecture notes or recordings or course materials in any other way (whether or not a fee is charged) without my express prior written consent. You also may not allow others to do so. Violations will be reported to the Office of Student Support and Judicial Affairs and may be subject to student conduct proceedings under the UC Davis Code of Academic Conduct.

## **Credits**

This course draws on code, content, ideas, inspirations and much more from work by Juan Tellez, Chris Hare, Mine Çetinkaya-Rundel, Andrew Heiss, Nick C. Huntington-Klein, Kieran Healy, Scott Cunningham, Richard McElreath and others who have made their courses publicly available. The lecture slides were developed by Juan Tellez and edited by me to fit the course.
