---
title: "POL 051: The Scientific Study of Politics"
tbl-colwidths: [8,15,55,11,11]
editor: source
---

This page contains an outline of the topics and materials for the Fall 2026 discussion sections (A04, A05, A06). Note that this schedule will be updated as the quarter progresses, with all changes documented here.

| TA | Lecture | Discussion/Lab |
|:---|:---|:---|
| Haley Daarstad<br>569 Kerr Hall<br>hbdaarstad\@ucdavis.edu<br>Office Hours: Tue 12:00 - 3:00 PM | Tuesday & Thursday<br>3:10 pm - 4:30 pm<br>Wellman Hall 2 | Friday<br>A04: 9:00 am - 9:50 am<br>A05: 10:00 am - 10:50 am<br>A06: 11:00 am - 11:50 am<br>Kerr Hall 451 |
: {tbl-colwidths="[40,30,30]"}

| Week | Date | Topic | Readings | Slides |
|:--:|:--:|:---|:--:|:--:|
| [1](/weeks/week-1.html) | Fri, Sep 25 | Welcome to POL 051; R Basics | [📖](/weeks/week-1.html#prepare) | [🖥️](slides/lec-1.html) |
| 2 | Fri, Oct 2 | Data Visualization |  |  |
| 3 | Fri, Oct 9 | Data Wrangling |  |  |
| 4 | Fri, Oct 16 | Relationships |  |  |
| 5 | Fri, Oct 23 | Modeling |  |  |
| 6 | Fri, Oct 30 | Causality |  |  |
| 7 | Fri, Nov 6 | DAGs |  |  |
| 8 | Fri, Nov 13 | Uncertainty & Hypothesis Testing |  |  |
| 9 | Fri, Nov 20 | Prediction & Natural Experiments |  |  |
| 10 | Fri, Nov 27 | *No section - Thanksgiving holiday* |  |  |
| 11 | Fri, Dec 4 | Review & Wrap-up |  |  |
